#!/usr/bin/env python3
"""
Forward generator: Manual/modules_yaml/*.yaml -> 3 outputs.

1. src/ManualHelpData.hpp                    (VCV tooltip, binary-compatible with Manual.cpp)
2. Manual/madzine_modules_compact_v5.0.html  (VCV-side manual, OKLCH palette)
3. madzine-website/modules.html              (website mirror)

All three outputs are derived from the same YAML source of truth.

Usage: python3 Manual/generate.py
"""

import base64
import json
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
YAML_DIR = ROOT / "Manual" / "modules_yaml"
PLUGIN_JSON = ROOT / "plugin.json"
IMG_DIR = ROOT / "Manual" / "modules"

HPP_OUT = ROOT / "src" / "ManualHelpData.hpp"
HTML_VCV_OUT = ROOT / "Manual" / "madzine_modules_compact_v5.0.html"
HTML_WEBSITE_OUT = Path("/Users/madzine/Documents/madzine-website/modules.html")

# Populated by load_image_cache(); maps img stem -> "data:image/png;base64,..."
IMG_DATA_URIS = {}


def load_image_cache():
    """Base64-encode every PNG in Manual/modules once; return dict[stem] -> data URI."""
    cache = {}
    if not IMG_DIR.is_dir():
        return cache
    for p in sorted(IMG_DIR.glob("*.png")):
        with p.open("rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        cache[p.stem] = f"data:image/png;base64,{b64}"
    return cache


def load_yamls():
    """Return dict[slug] -> parsed YAML doc."""
    docs = {}
    for p in sorted(YAML_DIR.glob("*.yaml")):
        with p.open("r", encoding="utf-8") as f:
            doc = yaml.safe_load(f)
        if not doc:
            continue
        docs[doc["slug"]] = doc
    return docs


def escape_cpp(s):
    """Escape a Python string for a C++ double-quoted literal."""
    if s is None:
        return ""
    out = []
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == "\"":
            out.append("\\\"")
        elif c == "\n":
            out.append("\\n")
        elif c == "\r":
            out.append("\\r")
        elif c == "\t":
            out.append("\\t")
        else:
            out.append(c)
    return "".join(out)


# --------------------------------------------------------------------------- #
# Output 1: ManualHelpData.hpp
# --------------------------------------------------------------------------- #

HPP_HEADER = """// Auto-generated by Manual/generate.py
// Do not edit manually
#pragma once
#include <string>
#include <map>
#include <vector>
#include <algorithm>

struct HelpEntry {
    std::string en;
    std::string zh;
    std::string ja;
    const std::string& get(const std::string& lang) const {
        if (lang == "zh") return zh;
        if (lang == "ja") return ja;
        return en;
    }
};

struct ModuleHelpData {
    std::string name;
    HelpEntry description;
    std::vector<std::pair<std::string, HelpEntry>> entries;
};

inline std::map<std::string, ModuleHelpData> initHelpData() {
    std::map<std::string, ModuleHelpData> data;
"""

HPP_FOOTER = "    return data;\n}\n"


def generate_hpp(docs):
    """Produce ManualHelpData.hpp content from YAML docs."""
    # Match current convention: iterate in alphabetical slug order (std::map order
    # is irrelevant at runtime, but the file is readable that way and matches the
    # old generator's ordering, keeping diffs minimal).
    # Skip 'Manual' (plugin.json stub with no controls/image).
    slugs = [s for s in sorted(docs.keys()) if s != "Manual"]
    lines = [HPP_HEADER]

    for slug in slugs:
        doc = docs[slug]
        entries = doc.get("controls", []) or []
        name = doc.get("name", slug)
        desc = doc.get("description", {}) or {}
        en = escape_cpp(desc.get("en", ""))
        zh = escape_cpp(desc.get("zh", ""))
        ja = escape_cpp(desc.get("ja", ""))

        lines.append(f"    // {slug} ({len(entries)} entries)\n")
        lines.append("    {\n")
        lines.append("        ModuleHelpData m;\n")
        lines.append(f"        m.name = \"{escape_cpp(name)}\";\n")
        lines.append(
            f"        m.description = {{\"{en}\", \"{zh}\", \"{ja}\"}};\n"
        )
        for ctrl in entries:
            cname = escape_cpp(ctrl.get("name", ""))
            d = ctrl.get("desc", {}) or {}
            ce = escape_cpp(d.get("en", ""))
            cz = escape_cpp(d.get("zh", ""))
            cj = escape_cpp(d.get("ja", ""))
            lines.append(
                f"        m.entries.push_back({{\"{cname}\", {{\"{ce}\", \"{cz}\", \"{cj}\"}}}});\n"
            )
        lines.append(f"        data[\"{slug}\"] = std::move(m);\n")
        lines.append("    }\n")

    lines.append(HPP_FOOTER)
    return "".join(lines)


# --------------------------------------------------------------------------- #
# Output 2/3: HTML (OKLCH palette)
# --------------------------------------------------------------------------- #

OKLCH_CSS = """
:root {
  --accent: oklch(0.65 0.06 295);
  --accent-2: oklch(0.72 0.06 295);
  --bg-1: oklch(0.22 0.005 265);
  --bg-2: oklch(0.20 0.005 265);
  --bg-3: oklch(0.18 0.005 265);
  --border: oklch(0.30 0.008 265);
  --text: oklch(0.93 0.01 80);
  --text-mute: oklch(0.83 0.015 80);
  --text-dim: oklch(0.68 0.015 80);
}
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI',
               'Noto Sans CJK TC', 'Noto Sans CJK JP', sans-serif;
  background: var(--bg-3);
  color: var(--text);
  line-height: 1.5;
  font-size: 16px;
}
body { padding-bottom: 4rem; }
header {
  background: var(--bg-2);
  padding: 1.25rem 1.5rem;
  border-bottom: 1px solid var(--border);
  position: sticky; top: 0; z-index: 10;
}
.header-content {
  max-width: 1600px; margin: 0 auto;
  display: flex; justify-content: space-between;
  align-items: center; flex-wrap: wrap; gap: 1rem;
}
header h1 {
  font-size: 1.75rem; color: var(--accent);
  letter-spacing: 3px; font-weight: 600;
}
header p { color: var(--text-mute); font-size: 0.95rem; }
.lang-selector { display: flex; gap: 0.4rem; }
.lang-btn {
  padding: 0.4rem 0.9rem;
  border: 1px solid var(--border);
  background: transparent;
  color: var(--text);
  cursor: pointer;
  border-radius: 999px;
  font-size: 0.85rem;
  transition: all 0.2s ease;
}
.lang-btn:hover { border-color: var(--accent); color: var(--accent); }
.lang-btn.active {
  background: var(--accent); color: var(--bg-3);
  border-color: var(--accent);
}
main { max-width: 1600px; margin: 0 auto; padding: 1.5rem 1rem; }
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 1rem;
}
.card {
  background: var(--bg-1);
  border: 1px solid var(--border);
  border-radius: 10px;
  overflow: hidden;
  transition: border-color 0.2s ease, transform 0.2s ease;
  cursor: pointer;
}
.card:hover {
  border-color: var(--accent);
  transform: translateY(-2px);
}
.card-top {
  display: flex; gap: 0.75rem;
  padding: 0.75rem;
  border-bottom: 1px solid var(--border);
}
.card-img img { height: 120px; width: auto; border-radius: 4px; }
.card-info { flex: 1; min-width: 0; }
.card-info h3 {
  font-size: 1.1rem; color: var(--accent);
  margin-bottom: 0.25rem; font-weight: 600;
}
.card-info .hp {
  font-size: 0.75rem; color: var(--text-dim);
  display: block; margin-bottom: 0.3rem;
}
.card-info p {
  font-size: 0.85rem; color: var(--text-mute);
  line-height: 1.4;
}
.features { padding: 0.6rem 0.75rem; }
.features h4 {
  font-size: 0.75rem; color: var(--accent-2);
  margin-bottom: 0.3rem; text-transform: uppercase;
  letter-spacing: 0.05em;
}
.features ul { padding-left: 1rem; }
.features li {
  font-size: 0.8rem; color: var(--text-mute);
  margin-bottom: 0.15rem;
}
/* Modal / detail view */
.modal {
  display: none; position: fixed; inset: 0;
  background: rgba(0,0,0,0.75); z-index: 100;
  padding: 2rem;
  overflow: auto;
}
.modal.open { display: block; }
.modal-content {
  background: var(--bg-2);
  border: 1px solid var(--border);
  border-radius: 12px;
  max-width: 1000px; margin: 0 auto;
  padding: 1.5rem;
  position: relative;
}
.modal-close {
  position: absolute; top: 0.5rem; right: 0.75rem;
  font-size: 1.5rem; cursor: pointer;
  color: var(--text-mute);
  background: transparent; border: 0;
}
.modal-close:hover { color: var(--accent); }
.modal-title { font-size: 1.5rem; color: var(--accent); margin-bottom: 0.25rem; }
.modal-hp { font-size: 0.85rem; color: var(--text-dim); }
.modal-desc { margin: 1rem 0; color: var(--text-mute); }
.manual-body {
  margin-top: 1.25rem;
  color: var(--text);
}
.manual-body h3 {
  color: var(--accent);
  border-bottom: 1px solid var(--border);
  padding-bottom: 0.3rem;
  margin: 1.2rem 0 0.6rem;
  font-size: 1.05rem;
}
.manual-body ul { padding-left: 1.3rem; margin-bottom: 0.75rem; }
.manual-body li { margin-bottom: 0.25rem; color: var(--text-mute); font-size: 0.9rem; }
.manual-body p { margin-bottom: 0.75rem; color: var(--text-mute); font-size: 0.9rem; }
.manual-body b { color: var(--text); }
footer {
  text-align: center; padding: 2rem 1rem;
  color: var(--text-dim); font-size: 0.8rem;
}
.lang-hidden { display: none; }
"""


JS_CONTROLLER = """
(function() {
  const langs = ['en', 'zh', 'ja'];
  let current = 'en';

  function applyLang(lang) {
    current = lang;
    document.querySelectorAll('[data-lang-group]').forEach(el => {
      el.classList.toggle('lang-hidden', el.dataset.langGroup !== lang);
    });
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === lang);
    });
    document.documentElement.lang = lang;
  }

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.dataset.lang));
  });

  // Card click -> modal
  const modal = document.getElementById('modal');
  const closeBtn = document.querySelector('.modal-close');

  function closeModal() { modal.classList.remove('open'); }
  closeBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });

  document.querySelectorAll('.card').forEach(card => {
    card.addEventListener('click', () => {
      const slug = card.dataset.slug;
      const tpl = document.getElementById('modal-tpl-' + slug);
      if (!tpl) return;
      document.querySelector('.modal-body').innerHTML = tpl.innerHTML;
      // Re-apply current language inside the freshly-cloned modal subtree.
      applyLang(current);
      modal.classList.add('open');
    });
  });

  applyLang('en');
})();
"""


def html_escape(s):
    if s is None:
        return ""
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def lang_span(value_map, tag="p"):
    """Render three spans (en/zh/ja), one visible per active language."""
    parts = []
    for lang in ("en", "zh", "ja"):
        val = (value_map or {}).get(lang, "") or ""
        parts.append(
            f'<{tag} data-lang-group="{lang}">{html_escape(val)}</{tag}>'
        )
    return "".join(parts)


def lang_list(list_map):
    parts = []
    for lang in ("en", "zh", "ja"):
        items = (list_map or {}).get(lang) or []
        lis = "".join(f"<li>{html_escape(x)}</li>" for x in items)
        parts.append(
            f'<ul data-lang-group="{lang}">{lis}</ul>'
        )
    return "".join(parts)


def lang_html_raw(html_map):
    """manual_html_raw: insert raw HTML (already trusted, came from our own files)."""
    parts = []
    for lang in ("en", "zh", "ja"):
        raw = (html_map or {}).get(lang, "") or ""
        parts.append(f'<div data-lang-group="{lang}">{raw}</div>')
    return "".join(parts)


def render_card(doc, img_dir):
    """Small card for grid view."""
    slug = doc["slug"]
    name = html_escape(doc.get("name", slug))
    hp = doc.get("hp")
    hp_txt = f"{hp} HP" if hp is not None else ""
    stem = slug_to_img_stem(doc)
    img_src = IMG_DATA_URIS.get(stem) or f"{img_dir}/{stem}.png"
    desc_html = lang_span(doc.get("description"))
    feat_map = doc.get("features") or {}
    # Show first 3 features in card.
    feat_short = {
        lang: (feat_map.get(lang) or [])[:3] for lang in ("en", "zh", "ja")
    }
    return f"""
    <article class="card" data-slug="{slug}">
      <div class="card-top">
        <div class="card-img"><img src="{img_src}" alt="{html_escape(doc.get('alt') or name)}"></div>
        <div class="card-info">
          <h3>{name}</h3>
          <span class="hp">{hp_txt}</span>
          {desc_html}
        </div>
      </div>
      <div class="features">
        <h4 data-lang-group="en">Features</h4>
        <h4 data-lang-group="zh">功能</h4>
        <h4 data-lang-group="ja">機能</h4>
        {lang_list(feat_short)}
      </div>
    </article>
    """


def render_modal_template(doc, img_dir):
    """Hidden <template> carrying full manual detail per module."""
    slug = doc["slug"]
    name = html_escape(doc.get("name", slug))
    hp = doc.get("hp")
    hp_txt = f"{hp} HP" if hp is not None else ""
    stem = slug_to_img_stem(doc)
    img_src = IMG_DATA_URIS.get(stem) or f"{img_dir}/{stem}.png"
    return f"""
    <template id="modal-tpl-{slug}">
      <button class="modal-close" aria-label="Close">&times;</button>
      <h2 class="modal-title">{name}</h2>
      <span class="modal-hp">{hp_txt}</span>
      <div class="modal-img"><img src="{img_src}" alt="{html_escape(doc.get('alt') or name)}" style="max-width:240px;border-radius:6px;margin:0.75rem 0;"></div>
      <div class="modal-desc">{lang_span(doc.get('description'))}</div>
      <div class="features">
        <h4 data-lang-group="en">Features</h4>
        <h4 data-lang-group="zh">功能</h4>
        <h4 data-lang-group="ja">機能</h4>
        {lang_list(doc.get('features') or {})}
      </div>
      <div class="manual-body">
        {lang_html_raw(doc.get('manual_html_raw'))}
      </div>
    </template>
    """


def slug_to_img_stem(doc):
    """Best-effort mapping from slug -> lower-snake filename used in modules/ assets."""
    # If YAML had an image hint, prefer it; else fall back to snake_case.
    slug = doc["slug"]
    # Known special cases from migrate_to_yaml.py SLUG_TO_FILE:
    overrides = {
        "SwingLFO": "swing_lfo",
        "EuclideanRhythm": "euclidean_rhythm",
        "ADGenerator": "ad_generator",
        "PPaTTTerning": "ppattterning",
        "TWNCLight": "twnc_light",
        "TWNC2": "twnc_2",
        "QQ": "q_q",
        "DECAPyramid": "decapyramid",
        "EllenRipley": "ellen_ripley",
        "MADDYPlus": "maddy_",
        "EnvVCA6": "env_vca_6",
        "WeiiiDocumenta": "weiii_documenta",
        "UniversalRhythm": "universal_rhythm",
        "UniRhythm": "uni_rhythm",
        "SongMode": "songmode",
        "ALEXANDERPLATZ": "alexanderplatz",
        "SHINJUKU": "shinjuku",
        "theKICK": "thekick",
    }
    if slug in overrides:
        return overrides[slug]
    return slug.lower()


def generate_html(docs, img_dir="modules"):
    """Produce one HTML string with all cards + modal templates."""
    slugs = sorted(docs.keys())
    # Skip the 'Manual' slug from cards if present (no JSON, no image).
    card_slugs = [s for s in slugs if s != "Manual"]

    cards = "\n".join(render_card(docs[s], img_dir) for s in card_slugs)
    templates = "\n".join(render_modal_template(docs[s], img_dir) for s in card_slugs)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MADZINE Modules</title>
  <style>{OKLCH_CSS}</style>
</head>
<body>
  <header>
    <div class="header-content">
      <div class="header-title">
        <h1>MADZINE</h1>
        <p data-lang-group="en">VCV Rack Modules</p>
        <p data-lang-group="zh">VCV Rack 模組</p>
        <p data-lang-group="ja">VCV Rack モジュール</p>
      </div>
      <div class="lang-selector">
        <button class="lang-btn active" data-lang="en">English</button>
        <button class="lang-btn" data-lang="zh">中文</button>
        <button class="lang-btn" data-lang="ja">日本語</button>
      </div>
    </div>
  </header>
  <main>
    <section class="grid">
{cards}
    </section>
  </main>

  <div id="modal" class="modal" role="dialog" aria-modal="true">
    <div class="modal-content">
      <div class="modal-body"></div>
    </div>
  </div>

{templates}

  <footer>
    <p>MADZINE VCV Rack Modules</p>
  </footer>

  <script>{JS_CONTROLLER}</script>
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    dry_run = "--dry-run" in sys.argv
    skip_website = "--no-website" in sys.argv or dry_run

    if not YAML_DIR.is_dir():
        print(f"ERROR: missing {YAML_DIR} (run migrate_to_yaml.py first)", file=sys.stderr)
        sys.exit(1)

    docs = load_yamls()
    if not docs:
        print("ERROR: no YAML files found", file=sys.stderr)
        sys.exit(1)

    global IMG_DATA_URIS
    IMG_DATA_URIS = load_image_cache()
    print(f"Loaded {len(IMG_DATA_URIS)} PNG assets as base64 data URIs")

    # Output 1: hpp
    hpp_text = generate_hpp(docs)
    if not dry_run:
        HPP_OUT.write_text(hpp_text, encoding="utf-8")
        print(f"Wrote {HPP_OUT}  ({len(hpp_text):,} bytes, {len([s for s in docs if s != 'Manual'])} modules)")
    else:
        print(f"[dry-run] would write {HPP_OUT}  ({len(hpp_text):,} bytes)")

    # HTML outputs removed: VCV-side HTML deprecated, website is hand-maintained.
    # Only hpp is generated (consumed by src/Manual.cpp tooltip).


if __name__ == "__main__":
    main()
