#!/usr/bin/env python3
"""Generate ManualHelpData.hpp from TSV data files."""

import csv
import os
import sys


def escape_cpp(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    s = s.replace('\t', '\\t')
    return s


def read_tsv(path):
    """Read a TSV file and return list of dicts (one per row)."""
    rows = []
    with open(path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            rows.append(row)
    return rows


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(base_dir, 'data')
    output_path = os.path.join(base_dir, '..', 'src', 'ManualHelpData.hpp')

    # --- Read modules.tsv ---
    modules_tsv = os.path.join(data_dir, 'modules.tsv')
    if not os.path.exists(modules_tsv):
        print(f'ERROR: {modules_tsv} not found')
        sys.exit(1)

    modules = read_tsv(modules_tsv)
    print(f'  Read {len(modules)} modules from modules.tsv')

    # --- Read controls.tsv (optional) ---
    controls_tsv = os.path.join(data_dir, 'controls.tsv')
    controls_by_module = {}
    if os.path.exists(controls_tsv):
        controls = read_tsv(controls_tsv)
        for row in controls:
            slug = row['module_slug']
            if slug not in controls_by_module:
                controls_by_module[slug] = []
            controls_by_module[slug].append(row)
        print(f'  Read {len(controls)} controls from controls.tsv')
    else:
        print(f'  WARNING: {controls_tsv} not found, skipping controls')

    # --- Generate C++ header ---
    lines = []
    lines.append('// Auto-generated by Manual/generate_help_data.py')
    lines.append('// Do not edit manually')
    lines.append('#pragma once')
    lines.append('#include <string>')
    lines.append('#include <map>')
    lines.append('#include <vector>')
    lines.append('#include <algorithm>')
    lines.append('')
    lines.append('struct HelpEntry {')
    lines.append('    std::string en;')
    lines.append('    std::string zh;')
    lines.append('    std::string ja;')
    lines.append('    const std::string& get(const std::string& lang) const {')
    lines.append('        if (lang == "zh") return zh;')
    lines.append('        if (lang == "ja") return ja;')
    lines.append('        return en;')
    lines.append('    }')
    lines.append('};')
    lines.append('')
    lines.append('struct ModuleHelpData {')
    lines.append('    std::string name;')
    lines.append('    HelpEntry description;')
    lines.append('    std::vector<std::pair<std::string, HelpEntry>> entries;')
    lines.append('};')
    lines.append('')
    lines.append('inline std::map<std::string, ModuleHelpData> initHelpData() {')
    lines.append('    std::map<std::string, ModuleHelpData> data;')

    total_entries = 0

    for mod in sorted(modules, key=lambda m: m['module_slug']):
        slug = mod['module_slug']
        name = mod['name']
        desc_zh = mod['desc_zh']
        desc_en = mod.get('desc_en', '') or desc_zh
        desc_ja = mod.get('desc_ja', '') or desc_zh

        entries = controls_by_module.get(slug, [])

        lines.append(f'    // {slug} ({len(entries)} entries)')
        lines.append('    {')
        lines.append('        ModuleHelpData m;')
        lines.append(f'        m.name = "{escape_cpp(name)}";')
        lines.append(f'        m.description = {{"{escape_cpp(desc_en)}", "{escape_cpp(desc_zh)}", "{escape_cpp(desc_ja)}"}};')

        for entry in entries:
            ename = entry['display_name']
            edesc_zh = entry['desc_zh']
            edesc_en = entry.get('desc_en', '') or edesc_zh
            edesc_ja = entry.get('desc_ja', '') or edesc_zh
            lines.append(f'        m.entries.push_back({{"{escape_cpp(ename)}", {{"{escape_cpp(edesc_en)}", "{escape_cpp(edesc_zh)}", "{escape_cpp(edesc_ja)}"}}}});')
            total_entries += 1

        lines.append(f'        data["{slug}"] = std::move(m);')
        lines.append('    }')

    lines.append('    return data;')
    lines.append('}')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Generated {output_path}')
    print(f'  {len(modules)} modules, {total_entries} entries total')


if __name__ == '__main__':
    main()
